# -*- coding: utf-8 -*-
"""仓库凭据的加密密钥**绝不能**回退到公开常量。

## 缺陷

`utils/security_utils._derive_fernet_key()` 原先的兜底是：

    os.environ.get("FLASK_SECRET_KEY") or os.environ.get("SECRET_KEY") or "diff-platform-local-key"

`"diff-platform-local-key"` 是**逐字节写在公开仓库里**的常量。它派生的 Fernet
密钥用来加解密仓库凭据（git/SVN 的 token 与口令，见 `encrypt_credential` /
`decrypt_credential`）。于是「没配 FLASK_SECRET_KEY」的部署会把所有仓库凭据用
公开密钥加密 —— 任何拿到数据库备份或导出的人都能直接解出全部 token。

这比 `FLASK_SECRET_KEY` 可猜更严重：那个只能伪造会话，这个能直接还原凭据。

注意 `utils/env_bootstrap.py` 的启动校验已经把 `diff-platform-local-key` 列进
占位值黑名单，但那只能拦住「**显式**把它填进 .env」—— 「压根不配置」才是原来的
实际路径，黑名单拦不住。所以必须在派生处修。

## 本文件断言什么

1. 没有任何密钥配置时，**公开常量解不开**新加密的值（核心断言）；
2. 自动生成的密钥**落盘**且跨进程稳定 —— 纯 per-process 随机虽然也不再是公开
   常量，但会让重启后旧值全部解不开，等于库里已存的凭据集体作废；
3. 显式配置的 `CREDENTIAL_ENCRYPTION_KEY` 仍然优先（不能被自动生成顶掉）；
4. 测试里不再出现那个常量作为「预期密钥」。
"""
from __future__ import annotations

import base64
import hashlib
import os
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest
from cryptography.fernet import Fernet

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from utils import security_utils  # noqa: E402

_PUBLIC_CONSTANT = "diff-platform-local-key"
_SECRET_ENV_NAMES = ("CREDENTIAL_ENCRYPTION_KEY", "FLASK_SECRET_KEY", "SECRET_KEY")


def _fernet_for_public_constant() -> Fernet:
    """用公开常量按原实现的方式派生一个 Fernet。"""
    digest = hashlib.sha256(_PUBLIC_CONSTANT.encode("utf-8")).digest()
    return Fernet(base64.urlsafe_b64encode(digest))


@pytest.fixture()
def without_secret_env(monkeypatch, tmp_path):
    """清掉三个密钥环境变量，并把自动密钥落到临时目录。"""
    for name in _SECRET_ENV_NAMES:
        monkeypatch.delenv(name, raising=False)
    monkeypatch.setattr(security_utils, "_auto_key_cache", None)
    yield
    monkeypatch.setattr(security_utils, "_auto_key_cache", None)


class TestPublicConstantCannotDecrypt:
    def test_token_is_not_decryptable_with_the_public_constant(self, without_secret_env):
        token = security_utils.encrypt_credential("my-super-secret-token")
        assert token.startswith(security_utils.ENCRYPTION_PREFIX)

        from cryptography.fernet import InvalidToken

        with pytest.raises(InvalidToken):
            _fernet_for_public_constant().decrypt(
                token[len(security_utils.ENCRYPTION_PREFIX) :].encode()
            )

    def test_roundtrip_still_works(self, without_secret_env):
        token = security_utils.encrypt_credential("my-super-secret-token")
        assert security_utils.decrypt_credential(token) == "my-super-secret-token"

    def test_source_has_no_hardcoded_fallback_constant(self):
        """源码级：那个常量不许再作为**字符串字面量**出现在代码里。

        用 AST 而不是文本匹配：本意是「不许作为兜底密钥」，而修复说明的
        docstring 里必须提到它（否则后来的人不知道为什么不能这么写）。
        文本匹配会把自己的说明当成违规 —— 这类「测试把解释当成违规」的坑，
        在仓库里已经出现过好几次。
        """
        import ast

        tree = ast.parse(
            (PROJECT_ROOT / "utils" / "security_utils.py").read_text(encoding="utf-8")
        )

        docstrings = set()
        for node in ast.walk(tree):
            if isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                body = getattr(node, "body", None)
                if body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant):
                    if isinstance(body[0].value.value, str):
                        docstrings.add(id(body[0].value))

        offenders = [
            (node.lineno, node.value)
            for node in ast.walk(tree)
            if isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and node.value == _PUBLIC_CONSTANT
            and id(node) not in docstrings
        ]
        assert not offenders, (
            f"security_utils.py 的**代码**里又出现了硬编码兜底密钥 {offenders} —— "
            "没有配置密钥的部署会用公开常量加密仓库凭据。"
        )


class TestAutoGeneratedKeyIsPersisted:
    def test_key_file_is_written_and_reused_across_reload(self, without_secret_env, tmp_path):
        """落盘 + 跨模块重载稳定：否则重启后旧值解不开。"""
        token = security_utils.encrypt_credential("persist-me")

        # 模拟「进程重启」：丢掉内存缓存，重新解密
        security_utils._auto_key_cache = None
        assert security_utils.decrypt_credential(token) == "persist-me"

    def test_key_file_lives_under_the_instance_directory(self, without_secret_env):
        security_utils.encrypt_credential("x")
        key_path = PROJECT_ROOT / "instance" / security_utils._AUTO_KEY_FILENAME
        assert key_path.exists(), f"自动密钥没有落盘：{key_path}"
        assert key_path.stat().st_size >= 32, "自动密钥太短，熵不足"

    def test_two_processes_agree_on_the_same_key(self):
        """真正的跨进程验证（内存缓存骗不过子进程）。"""
        script = textwrap.dedent(
            """
            import os, sys
            for name in ("CREDENTIAL_ENCRYPTION_KEY", "FLASK_SECRET_KEY", "SECRET_KEY"):
                os.environ.pop(name, None)
            sys.path.insert(0, os.getcwd())
            from utils import security_utils as su
            print(su._derive_fernet_key().decode("latin-1"))
            """
        )
        outputs = []
        for _ in range(2):
            result = subprocess.run(
                [sys.executable, "-c", script],
                cwd=str(PROJECT_ROOT),
                capture_output=True,
                text=True,
                encoding="latin-1",
                errors="replace",
            )
            assert result.returncode == 0, result.stderr
            outputs.append(result.stdout.strip().splitlines()[-1])
        assert outputs[0] == outputs[1], (
            "两个进程派生出了不同的密钥 —— 落盘复用没生效，"
            "表现为「重启后库里的仓库凭据全部解不开」"
        )


class TestExplicitKeyStillWins:
    def test_credential_encryption_key_takes_priority(self, monkeypatch, tmp_path):
        monkeypatch.setenv("CREDENTIAL_ENCRYPTION_KEY", "explicit-key-for-test")
        monkeypatch.setattr(security_utils, "_auto_key_cache", None)

        from cryptography.hazmat.primitives import hashes
        from cryptography.hazmat.primitives.kdf.hkdf import HKDF  # noqa: F401  (仅确认可选依赖可用)

        digest = hashlib.sha256(b"explicit-key-for-test").digest()
        expected = Fernet(base64.urlsafe_b64encode(digest))
        token = security_utils.encrypt_credential("explicit-path")
        expected.decrypt(token[len(security_utils.ENCRYPTION_PREFIX) :].encode())

    def test_flask_secret_key_is_used_when_present(self, monkeypatch):
        monkeypatch.delenv("CREDENTIAL_ENCRYPTION_KEY", raising=False)
        monkeypatch.setenv("FLASK_SECRET_KEY", "flask-secret-for-test")
        monkeypatch.setattr(security_utils, "_auto_key_cache", None)

        digest = hashlib.sha256(b"flask-secret-for-test").digest()
        expected = Fernet(base64.urlsafe_b64encode(digest))
        token = security_utils.encrypt_credential("flask-path")
        expected.decrypt(token[len(security_utils.ENCRYPTION_PREFIX) :].encode())
